site_name: Literate Programming in R
nav:
    - About: index.md
    - Course Content:
      - "1. The concepts and goals of Literate Programming": chapters/chapter_01.md
      - "2. The Literate Programming Approach: A Primer": chapters/chapter_02.md
      - "3. Writing prose for Literate Programming with Markdown: an Introduction": chapters/chapter_03.md
      - "4. An Introduction to Quarto": chapters/Chapter_04.md
      - "5. Conclusion and next steps": chapters/chapter_05.md
      - "References": chapters/references.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-LiterateProgrammingR-CodeRep
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

